GET  http://localhost:8080/api/emp
Content-Type: application/json

###

GET  http://localhost:8080/api/emp/param/3
Content-Type: application/json

###

POST http://localhost:8080/api/emp
Accept: application/json
Content-Type: application/json

{
"name" : "Bill Doe"
}

###

PUT http://localhost:8080/api/emp/param/2
Accept: application/json
Content-Type: application/json

{
  "name" : "Jane Doe"
}

###

DELETE http://localhost:8080/api/emp/param/2
