GET http://localhost:8080/api/instruments
Accept: application/json

###

POST http://localhost:8080/api/instruments
Content-Type: application/json

{
  "brand" : "kocsogduda",
  "type" : "PIANO",
  "price" : 1400
}

###

POST http://localhost:8080/api/instruments
Content-Type: application/json

{
  "brand" : "",
  "type" : "PIANO",
  "price" : 1400
}

###

